@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> Master: 请求，携带(files,R)
Client -> Master: 请求分派任务
Master -> Client: 提供file，执行Map
Client -> Master: 提交Map任务
Master -> Client: 分配执行Reduce
Client -> Client2: 请求获取Reduce的中间结果
Client2 -> Client: 响应中间结果
Client -> Master: 原子提交，响应结果文件
Master -> User: 唤醒用户进程
@enduml