@startuml
'https://plantuml.com/sequence-diagram

autonumber

Master -> Client: ping
Client -> Master: response
Master -> Client: ping(失败)
Master -> Client2: 分配原来Client1的Map任务map_job
Master -> Clients: 通知，将map_job的对应节点从Client1改为Client2

@enduml